### ISSUE TITLE
Requirements of Guidelines and Instructions

### ISSUE THREAD

**Issue by ghost** [cclvi256/Data-Structure-and-Algorithms-Labs#1]
Thank you for your contribution!
 I have cloned this repository, but I found it hard to run your programs. So could you add some instructions to tell us how to run them on our device?
By the way, I don't know the guideline of the labs and assignments, could you please add them to each directory?

**Comment by cider-apple** [comment]
Thank you for your interest in this repository. I'll complete these contents no later than this August. If you're in a desire of these, it's also appreciated for you to search the CMake instructions online.
